<?php

/**
 * Implements hook_menu()
 *
 * @return array
 */
function badgekit_menu() {
  $items = array();

  $items['badges'] = array(
    'title' => 'Published Badges',
    'page callback' => 'badgekit_page',
    'access callback' => TRUE,
    'weight' => -10,
    'file' => 'badgekit.pages.inc',
  );

  $items['admin/settings/badgekit'] = array(
    'title' => 'Badgekit module settings',
    'description' => 'Set Badgekit API URL and secret',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('badgekit_admin'),
    'access arguments' => array('administer badgekit settings'),
    'file' => 'badgekit.pages.inc',
  );

  return $items;
}


/**
 * Implements hook_permission().
 */
function badgekit_permission() {
  return array(
    'administer badgekit settings' => array(
      'title' => t('Administer Badgekit module settings'),
    )
  );
}


/**
 * Implements hook_theme().
 */
function badgekit_theme() {
  $items['badge'] = array(
    'file' => 'badgekit.theme.inc',
    'variables' => array(
      'badge' => array(),
    ),
  );
  return $items;
}
